language: node_js

sudo: required

dist: xenial

node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'
  - sed -i 's/your_token/${BAIDU_PUSH_TOKEN}/g' ./_config.yml

install:
  - npm install --pure-lockfile

script:
  - hexo g
  - hexo d

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  committer-from-gh: true
  name: $U_NAME
  email: $U_EMAIL
  github_token: $GH_TOKEN  
  keep-history: true
  target-branch: $P_BRANCH
  on:
    branch: master
