# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: '叉叉白'
subtitle: '叉叉白，听我跟你瞎白话'
description: '一个小白搞机的记事本'
keywords: 
  叉叉白
  搞机
  小白
  安卓
  Xposed
  Magisk
  刷机
  救砖
  Unity
  Hexo
  建站
author: 'MonoLogueChi'
language: 'Zh-cn'
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.xxwhite.com/
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: '*.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
  
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: '    '

markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: 'highlight'

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 
  
feed:
  limit: 35
  hub:
  content: true
  content_limit: 1000
  content_limit_delim: '。'

jsonContent: 
  meta: false
  pages: false
  posts: 
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true  
 
#APlayer
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js  # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  meting: true                                  # MetingJS 支持
  meting_api: https://sm.sm9.top/api.php
  #meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js # 引用 Meting.js 外部 CDN 地址 (默认不开启)
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@1.2/dist/Meting.min.js
  asset_inject: true                           # 自动插入 Aplayer.js 与 Meting.js 资源脚本, 默认开启

#DPlayer
hexo-tag-dplayer:
  cdn:
    - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
    - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.css
  default: 
    api: https://danmaku.xwhite.studio/api/dplayer/
    loop: yes
    screenshot: yes

#网页压缩
html_minifier:
  enable: false
  ignore_error: false
  exclude:
css_minifier:
  enable: false
  exclude:
    - '*.min.css'
js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
