# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "叉叉白"
subtitle: "叉叉白，听我跟你瞎白话"
description: "一个小白搞机的记事本"
keywords: 叉叉白,搞机,小白,安卓,Xposed,Magisk,刷机,救砖,Unity,Hexo,建站,网络,软路由
author: "MonoLogueChi"
language: "Zh-cn"
timezone: ""

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.xxwhite.com/
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "**/**.html"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: "    "

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ""
  autolink: false
  sanitizeUrl: false
  headerIds: true

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-checkbox
    - markdown-it-imsize
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: true
    permalinkClass: header-anchor
    permalinkSide: right
    permalinkSymbol: "➴"

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: baidu_url_submitter ##百度推送

baidu_url_submit:
  count: 3 ## 提交最新的一个链接
  host: blog.xxwhite.com ## 在百度站长平台中注册的域名
  token: your_token ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

feed:
  limit: 35
  hub:
  content: true
  content_limit: 1000
  content_limit_delim: "。"

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

mmedia:
  aplayer:
    default:
      order: random
  meting:
    api: https://sm.sm9.top/api.php
    default:
      order: random
  dplayer:
    default:
      loop: true
  bilibili:
    default:
      danmaku: true
      max_width: 950px
      margin: auto
  xigua:
    default:
      max_width: 950px
      margin: auto

#网页压缩
asset_pipeline:
  revisioning:
    enable: false
  clean_css:
    enable: false
  uglify_js:
    enable: false
  imagemin:
    enable: false
  html_minifier:
    enable: true