# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "叉叉白"
subtitle: "叉叉白，听我跟你瞎白话"
description: "一个小白搞机的记事本"
keywords: 叉叉白
  搞机
  小白
  安卓
  Xposed
  Magisk
  刷机
  救砖
  Unity
  Hexo
  建站
author: "MonoLogueChi"
language: "Zh-cn"
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.xxwhite.com/
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "**/**.html"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: "    "

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ""
  autolink: false
  sanitizeUrl: false
  headerIds: true

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: "v"
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ¶

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: baidu_url_submitter ##百度推送

baidu_url_submit:
  count: 3 ## 提交最新的一个链接
  host: blog.xxwhite.com ## 在百度站长平台中注册的域名
  token: your_token ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里


feed:
  limit: 35
  hub:
  content: true
  content_limit: 1000
  content_limit_delim: "。"

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

mmedia:
  aplayer: 
    cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
    style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
    default: 
      order: random
  meting:
    cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js
    api: https://sm.sm9.top/api.php
    default: 
      order: random
  dplayer:
    cdn: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
    style_cdn: https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.css
    default: 
      api: https://danmaku.xwhite.studio/api/dplayer/
      loop: true
      screenshot: true
  bilibili: 
    default: 
      quality: high
      danmaku: true
      width: 850px
      height: 550px
      margin: auto

#网页压缩
html_minifier:
  enable: true
  ignore_error: false
  exclude:
css_minifier:
  enable: false
  exclude:
    - "*.min.css"
js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

## 主题
theme_config:
  # Header
  menu:
    主页: '/'
    搞机: '/tags/搞机/'
    笔记: '/tags/建站笔记/'
    时光: '/tags/timeline/'
    留言: '/MessageBoard/'
    关于: '/aboutme/'

# SubNav
  subnav:
    github: 'https://github.com/MonoLogueChi'
    #weibo: "https://weibo.com/u/5226533927/"
    #zhihu: "#"
    qq: "/assets/html/qq-groups.html"
    #weixin: 'https://s1.ax2x.com/2018/07/14/q4v9K.png'
    #jianshu: "#"
    #douban: "#"
    #segmentfault: "#"
    bilibili: 'https://space.bilibili.com/28474682/'
    #acfun: "#"
    mail: 'mailto:xxwhite@foxmail.com'
    #facebook: "#"
    #google: "#"
    #twitter: "#"
    #linkedin: "#"
    rss: '/atom.xml'

  rss: '/atom.xml'

  # 是否需要修改 root 路径
  # 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
  # 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
  root:

  # Content

  # 文章太长，截断按钮文字
  excerpt_link: ''
  # 文章卡片右下角常驻链接，不需要请设置为false
  show_all_link: '展开全文'
  # 数学公式
  mathjax: false
  # 是否在新窗口打开链接
  open_in_new: false
  fancybox: true

  # 打赏
  # 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
  reward_type: 2
  # 打赏wording
  reward_wording: '请作者吃辣条'
  # 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
  alipay: '/assets/img/alipay.png'
  # 微信二维码图片地址
  weixin: '/assets/img/wechatpay.png'

  # 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有copyright不为false的文章均有版权声明
  copyright_type: 2

  # 备案信息，没有请留空
  beian: '蒙ICP备17004911号-1'

  # 又拍云开发者计划图片链接，没有请留空
  upyun: '/assets/img/upyun.png'

  # 目录
  # 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
  toc: 2
  # 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
  toc_hide_index: false
  # 目录为空时的提示
  toc_empty_wording: '目录，不存在的…'

  # 是否有快速回到顶部的按钮
  top: true

  # Miscellaneous
  baidu_analytics: '893dcb25b87bcda2f682b3a6d5c537f7'
  google_analytics: 'UA-113200574-1'
  favicon: '/assets/img/favicon.png'

  #你的头像url
  avatar: '/assets/img/avatar.jpg'

  #是否开启分享
  share_jia: false

  #评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
  #不需要使用某项，直接设置值为false，或注释掉
  #具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

  #1、多说
  duoshuo: false

  #2、网易云跟帖
  wangyiyun: false

  #3、畅言
  #changyan_appid: 
  #changyan_conf: 

  #4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
  disqus: false

  #5、Gitment
  gitment_owner: false      #你的 GitHub ID
  gitment_repo: ''          #存储评论的 repo
  gitment_oauth:
    client_id: ''           #client ID
    client_secret: ''       #client secret
  
  
  #6、Valine https://valine.js.org
  valine: 
    appid: 'BOnDPDiz9EeoGAC11JdnV9mw-gzGzoHsz' #Leancloud应用的appId
    appkey: 'gNFFgOahNl9DGsyX1WearaYO' #Leancloud应用的appId
    verify: false #验证码
    notify: false #评论回复提醒
    avatar: '' #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    avatar_cdn: 'https://sdn.geekzu.org/avatar/' #头像CDN
    placeholder: '友情提醒，留下正确的邮箱地址可以第一时间获取评论反馈' #评论框占位符
    pageSize: 12 #评论分页
    visitor: true #阅读统计
    recordIP: true #记录IP
    serverURLs: 'https://leancloud.xxwhite.com'

  # 样式定制 - 一般不需要修改，除非有很强的定制欲望…
  style:
    # 头像上面的背景颜色
    header: '#4d4d4d'
    # 右滑板块背景
    slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

  # slider的设置
  slider:
    # 是否默认展开tags板块
    showTags: false

  # MarkDown文件下载地址,如：http://md.xxwhite.com
  mdhost: 'https://raw.githubusercontent.com/MonoLogueChi/blog.xxwhite.com/master/source/_posts'
  # 网站建站日期
  wbd:
    y: 2015
    m: 03
    d: 08

  #pangu.js，中英文混排优化
  pangu: true

  # 智能菜单
  # 如不需要，将该对应项置为false
  # 比如
  #smart_menu:
  #  friends: false
  smart_menu:
    innerArchive: '所有文章'
    friends: '友链'
    aboutme: '关于本站'

  friends:
    叉叉白: 'https://blog.xxwhite.com/'
    大姐姐的博客Minemine: 'https://minemine.cc/'
    酷安基佬: 'http://socoolapk.top/'
    Se7en: 'https://www.se7ensec.cn/'
    姬长信: 'https://blog.isoyu.com/'
    staunchkai: 'http://staunchkai.com/'
    随遇而安: 'https://www.iszy.cc/'
    2401的晚秋咖啡: 'https://zsh2401.top/'
    Junzhou Liu: 'https://liujunzhou.top/'
    Yi-Yun: 'https://yi-yun.github.io/'  
    LmCjl在线工具: 'https://www.lmcjl.com'
    Freetao’s Blog: 'https://blogs.kainy.cn/'
  
  aboutme: 叉叉白 一个小白搞机的记事本
