trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github
- group: upyun
- group: search

steps:
- checkout: self
  fetchDepth: 1
  submodules: true

- task: UseNode@1
  inputs:
    version: "12.x"
    
- task: CmdLine@2
  inputs:
    script: |
      curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      pnpm add -g hexo-cli
      pnpm install
      sed -i 's/your_token/$(BAIDU_PUSH_TOKEN)/g' ./_config.yml
      pnpm start

      #又拍云同步
      wget -O upx http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.6
      chmod +x upx
      ./upx login $(BUCKET) $(OPERATOR) $(OPERATOR_PASSWORD)
      ./upx sync public/ / --delete
      ./upx logout
      
      #GitHub Page
      cd public
      touch .nojekyll
      git config --global user.email "$(EMAIL)"
      git config --global user.name "$(USER)"
      git init
      git add .
      git commit -m update
      git push --force --quiet https://$(TOKEN)@github.com/MonoLogueChi/blog.xxwhite.com.git master:gh-pages
